/*
	GENERATED BY THE BUILD SCRIPT AUTOMATICALLY 
	EDIT AT YOUR OWN RISK
*/

package com.dblfuzzr.jboss.auth.spi;

public  class VersionInfo
{

/// Version (Major) 
int VersionMajor = 0;

/// Version (Minor) 
int VersionMinor = 0;

/// Version (Build) 
int VersionBuildNo = 1;

/// Version Comment 
static public String VersionComment = "Installer Script $Rev: 142 $";

///  
static public String VersionStr = "0.0.1.0";

///  
static public String VersionProductName = "Fuzzrbox";

///  
static public String VersionFileDesc = "Java Classes For Fuzzrbox";

///  
static public String VersionCopyright = "Copyright (c) DblFuzzr,LLC 2013";

///  
static public String VersionSpecialBuild = "Pre-release build  ";

///  
static public String VersionPrivateBuild = " ";

///  
static public String VersionBuildDate = "Sun, Jan 10,2013 [23:59]";

/// End VersionInfo
}
